version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver_plus 0.0.0.0:8000 --insecure --cert /tmp/cert
    volumes:
      - .:/code
    ports:
      - 3000:3000
      - 8000:8000
      - 8010:8010
      - 9191:9191
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=YF9ZnHgdqwmVRWXXgK_fY-s4uxSee4kRF83SB1Gtz9s"
      - "DJANGO_DEBUG=False"
      - "VSCODE_DEBUGGER=False"

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432

volumes:
  postgres_data: