version: '3.8'

services:
  web:
    build: .
    command: ./runner.sh
    volumes:
      - .:/code
    ports:
      - 443:443
      - 3000:3000
      - 8000:8000
      - 8001:8001
      - 8080:8080
      - 8010:8010
      - 9191:9191
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=9j2p-v+e(wl7&de+3(73*$$z0fv_&0_(7$$-95(^obmd4v#mb_u3"
      - "DJANGO_DEBUG=False"
      - "VSCODE_DEBUGGER=False"

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432

volumes:
  postgres_data: